/**
 * generated by Xtext
 */
package org.correttouml.grammars.validation;

import org.correttouml.grammars.validation.AbstractPropertyValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PropertyValidator extends AbstractPropertyValidator {
}
