/**
 * generated by Xtext
 */
package org.correttouml.grammars.ui.contentassist;

import org.correttouml.grammars.ui.contentassist.AbstractPropertyProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PropertyProposalProvider extends AbstractPropertyProposalProvider {
}
